from __future__ import annotations

from typing import Any


def method_registry() -> list[dict[str, Any]]:
    values = [
        (
            "series_profile",
            "quality",
            "Native-series profile",
            1,
            False,
            False,
            False,
            "Completeness, regularity, dispersion, sparsity and distribution shape",
            "https://doi.org/10.1002/sim.4780130110",
        ),
        (
            "stl",
            "decomposition",
            "Robust STL decomposition",
            24,
            True,
            False,
            False,
            "Robust trend, seasonal and remainder decomposition",
            "https://doi.org/10.1080/01621459.1990.10475313",
        ),
        (
            "robust_residual_anomaly",
            "anomaly",
            "Robust residual anomaly detection",
            12,
            True,
            False,
            False,
            "Median absolute deviation anomaly scoring on decomposition residuals",
            "https://doi.org/10.1080/01621459.1974.10482962",
        ),
        (
            "robust_multivariate_anomaly",
            "anomaly",
            "Robust multivariate anomaly detection",
            12,
            True,
            False,
            False,
            "Joint robust-distance anomaly detection over level, change and residual magnitude",
            "https://doi.org/10.1214/aoms/1177728060",
        ),
        (
            "ewma",
            "surveillance",
            "EWMA surveillance statistic",
            12,
            True,
            False,
            False,
            "Exponentially weighted monitoring statistic for sustained shifts",
            "https://doi.org/10.1080/00401706.1959.10489854",
        ),
        (
            "pelt",
            "change_point",
            "PELT change-point detection",
            12,
            True,
            False,
            False,
            "Penalized exact segmentation for distributional changes",
            "https://doi.org/10.1080/01621459.2012.737745",
        ),
        (
            "adf",
            "stationarity",
            "Augmented Dickey-Fuller",
            12,
            True,
            False,
            False,
            "Unit-root diagnostic",
            "https://doi.org/10.1080/01621459.1979.10482531",
        ),
        (
            "kpss",
            "stationarity",
            "KPSS stationarity test",
            12,
            True,
            False,
            False,
            "Level-stationarity diagnostic",
            "https://doi.org/10.1016/0304-4076(92)90104-Y",
        ),
        (
            "ljung_box",
            "dependence",
            "Ljung-Box portmanteau test",
            12,
            True,
            False,
            False,
            "Residual serial-dependence diagnostic",
            "https://doi.org/10.1093/biomet/65.2.297",
        ),
        (
            "arch_lm",
            "dependence",
            "ARCH LM test",
            16,
            True,
            False,
            False,
            "Conditional heteroskedasticity diagnostic",
            "https://doi.org/10.2307/1912773",
        ),
        (
            "acf_pacf",
            "dependence",
            "ACF and PACF",
            8,
            True,
            False,
            False,
            "Lag dependence coordinates for autoregressive and seasonal specification",
            "https://www.statsmodels.org/stable/generated/statsmodels.tsa.stattools.acf.html",
        ),
        (
            "periodogram",
            "frequency",
            "Periodogram",
            12,
            True,
            False,
            False,
            "Dominant periodicity and spectral concentration",
            "https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.periodogram.html",
        ),
        (
            "wavelet",
            "frequency",
            "Continuous wavelet transform",
            24,
            True,
            False,
            False,
            "Time-localized periodicity and scale-dependent power",
            "https://doi.org/10.1175/1520-0477(1998)079%3C0061:APGTWA%3E2.0.CO;2",
        ),
        (
            "emd_hht",
            "decomposition",
            "Empirical mode decomposition and Hilbert-Huang diagnostics",
            24,
            True,
            False,
            False,
            "Intrinsic mode functions, instantaneous frequency and component energy",
            "https://doi.org/10.1098/rspa.1998.0193",
        ),
        (
            "hurst",
            "nonlinear",
            "Generalized Hurst scaling",
            24,
            True,
            False,
            False,
            "Long-memory and multiscale roughness diagnostic",
            "https://doi.org/10.1016/0165-1684(94)00117-F",
        ),
        (
            "higuchi_fd",
            "nonlinear",
            "Higuchi fractal dimension",
            24,
            True,
            False,
            False,
            "Fractal complexity of the observed trajectory",
            "https://doi.org/10.1016/0167-2789(88)90081-4",
        ),
        (
            "entropy",
            "nonlinear",
            "Entropy diagnostics",
            16,
            True,
            False,
            False,
            "Sample, permutation and spectral entropy",
            "https://doi.org/10.1103/PhysRevLett.88.174102",
        ),
        (
            "recurrence",
            "nonlinear",
            "Recurrence quantification",
            24,
            True,
            False,
            False,
            "Recurrence rate, determinism and laminarity of the reconstructed dynamics",
            "https://doi.org/10.1016/S0375-9601(02)01103-2",
        ),
        (
            "pca_biplot",
            "high_dimensional_geography",
            "PCA biplot",
            5,
            True,
            True,
            False,
            "Location scores and temporal loadings for high-dimensional geographic structure",
            "https://doi.org/10.1007/b98835",
        ),
        (
            "hgd",
            "high_dimensional_geography",
            "High-dimensional geography diagnostics",
            5,
            True,
            True,
            False,
            "Effective rank, participation ratio, concentration and geographic embedding stability",
            "https://doi.org/10.1038/s41598-026-63542-8",
        ),
        (
            "dynamic_mode_decomposition",
            "spatiotemporal",
            "Dynamic mode decomposition",
            8,
            True,
            True,
            False,
            "Coherent spatiotemporal modes, growth and oscillatory dynamics",
            "https://doi.org/10.1017/S0022112010001217",
        ),
        (
            "panel_synchrony",
            "spatiotemporal",
            "Panel synchrony and lead-lag",
            8,
            True,
            True,
            False,
            "Pairwise synchrony, maximum cross-correlation lag and propagation structure",
            "https://doi.org/10.1111/j.1466-8238.2005.00162.x",
        ),
        (
            "transfer_entropy",
            "spatiotemporal",
            "Discrete transfer entropy",
            16,
            True,
            True,
            False,
            "Directional information flow between geographic series",
            "https://doi.org/10.1103/PhysRevLett.85.461",
        ),
        (
            "moran_global",
            "spatial",
            "Global Moran I",
            1,
            False,
            True,
            True,
            "Global spatial autocorrelation with permutation inference",
            "https://doi.org/10.2307/2332142",
        ),
        (
            "geary_c",
            "spatial",
            "Geary C",
            1,
            False,
            True,
            True,
            "Global local-difference spatial autocorrelation",
            "https://doi.org/10.2307/2986645",
        ),
        (
            "semivariogram",
            "spatial",
            "Empirical semivariogram",
            1,
            False,
            True,
            True,
            "Distance-dependent spatial variance, range and sill diagnostics",
            "https://doi.org/10.1007/978-1-4612-0873-7",
        ),
        (
            "moran_local",
            "spatial",
            "Local Moran LISA",
            1,
            False,
            True,
            True,
            "Local spatial association and cluster/outlier classification",
            "https://doi.org/10.1111/j.1538-4632.1995.tb00338.x",
        ),
        (
            "getis_ord",
            "spatial",
            "Getis-Ord Gi star",
            1,
            False,
            True,
            True,
            "Local hot- and cold-spot diagnostic",
            "https://doi.org/10.1111/j.1538-4632.1992.tb00261.x",
        ),
        (
            "space_time_scan",
            "spatiotemporal",
            "Space-time scan statistic",
            8,
            True,
            True,
            True,
            "Likelihood-based prospective or retrospective space-time cluster detection",
            "https://doi.org/10.1080/03610929708831995",
        ),
        (
            "multiple_testing",
            "inference",
            "Benjamini-Hochberg FDR",
            1,
            False,
            False,
            False,
            "False-discovery-rate control within diagnostic families",
            "https://doi.org/10.1111/j.2517-6161.1995.tb02031.x",
        ),
    ]
    return [
        {
            "method_id": item[0],
            "method_family": item[1],
            "method_name": item[2],
            "method_version": "1.0.0",
            "minimum_periods": item[3],
            "requires_regular_time": item[4],
            "requires_multiple_locations": item[5],
            "requires_geometry": item[6],
            "description": item[7],
            "citation_url": item[8],
            "default_parameters": {},
        }
        for item in values
    ]
