from __future__ import annotations

import pandas as pd


def method_registry() -> pd.DataFrame:
    rows = [
        (
            "grain_inventory",
            "data_quality",
            "cases",
            "coverage and native versus derived grains",
            "all",
            "10.1038/s41597-024-03120-7",
        ),
        (
            "completeness_profile",
            "data_quality",
            "cases and dates",
            "missing periods and reporting gaps",
            "all",
            "10.1038/s41597-024-03120-7",
        ),
        (
            "cross_source_reconciliation",
            "data_quality",
            "overlapping sources",
            "source disagreement",
            "all",
            "10.1038/s41597-024-03120-7",
        ),
        (
            "zero_overdispersion",
            "temporal",
            "count series",
            "zero inflation and variance to mean ratio",
            "forecasting;transmission",
            "10.1016/j.sste.2020.100335",
        ),
        (
            "adf_kpss",
            "temporal",
            "ordered series",
            "stationarity and differencing need",
            "forecasting",
            "10.1016/j.heliyon.2022.e10350",
        ),
        (
            "acf_ljung_box",
            "temporal",
            "ordered series",
            "serial dependence and residual whiteness",
            "forecasting",
            "10.1016/j.heliyon.2022.e10350",
        ),
        (
            "stl",
            "temporal",
            "two seasonal cycles",
            "trend and seasonal strength",
            "forecasting;risk",
            "10.1016/j.heliyon.2022.e10350",
        ),
        (
            "periodogram",
            "temporal",
            "regular series",
            "dominant periodicity",
            "forecasting;transmission",
            "10.3390/insects15050366",
        ),
        (
            "continuous_wavelet",
            "temporal",
            "regular series",
            "time varying periodicity and phase",
            "forecasting;transmission",
            "10.3390/insects15050366",
        ),
        (
            "pelt_change_points",
            "temporal",
            "ordered series",
            "regime shifts and intervention breaks",
            "forecasting;transfer",
            "10.1038/s41598-022-13749-2",
        ),
        (
            "global_moran",
            "spatial",
            "areal values and adjacency",
            "global spatial autocorrelation",
            "risk;disaggregation",
            "10.1038/s41598-024-82212-1",
        ),
        (
            "geary_c",
            "spatial",
            "areal values and adjacency",
            "local difference sensitivity",
            "risk;disaggregation",
            "10.1038/s41598-024-82212-1",
        ),
        (
            "local_moran_lisa",
            "spatial",
            "areal values and adjacency",
            "high high and spatial outlier clusters",
            "risk",
            "10.1038/s41598-024-82212-1",
        ),
        (
            "getis_ord_gi_star",
            "spatial",
            "areal values and adjacency",
            "hot and cold spots",
            "risk",
            "10.1038/s41598-024-82212-1",
        ),
        (
            "semivariogram",
            "spatial",
            "coordinates and values",
            "spatial range and scale",
            "risk;disaggregation",
            "10.3390/insects15050366",
        ),
        (
            "spatial_scan_statistic",
            "spatiotemporal",
            "cases population coordinates dates",
            "statistically significant flexible clusters",
            "risk;transmission",
            "10.1038/s41598-024-82212-1",
        ),
        (
            "emerging_hotspot",
            "spatiotemporal",
            "local hot spot series",
            "new persistent intensifying and diminishing hot spots",
            "risk;forecasting",
            "10.1038/s41598-024-82212-1",
        ),
        (
            "dtw_clustering",
            "spatiotemporal",
            "multiple regular series",
            "shape based epidemic typologies",
            "transfer;forecasting",
            "10.3390/insects15050366",
        ),
        (
            "seasonal_phase",
            "spatiotemporal",
            "seasonal area series",
            "peak timing and propagation",
            "transmission;forecasting",
            "10.3390/insects15050366",
        ),
        (
            "space_time_variance",
            "spatiotemporal",
            "area by time matrix",
            "spatial temporal and interaction fractions",
            "all",
            "10.1038/s41598-024-82212-1",
        ),
        (
            "bayesian_car_rw2",
            "model_based",
            "counts population adjacency",
            "smoothed risk and space time interaction",
            "risk;forecasting",
            "10.1038/s41598-024-82212-1",
        ),
        (
            "bayesian_poisson_car",
            "model_based",
            "counts population adjacency covariates",
            "posterior relative risk",
            "risk;disaggregation",
            "10.4081/gh.2025.1379",
        ),
        (
            "dlnm",
            "model_based",
            "counts and time varying exposures",
            "nonlinear delayed exposure response",
            "forecasting;transmission",
            "10.3390/insects15050366",
        ),
        (
            "gam_gamm",
            "model_based",
            "counts covariates space time",
            "smooth nonlinear space time effects",
            "forecasting;risk",
            "10.1016/j.sste.2020.100335",
        ),
        (
            "space_time_varying_coefficient",
            "model_based",
            "longitudinal covariates",
            "nonstationary associations",
            "risk;transfer",
            "10.3390/math13121995",
        ),
        (
            "mobility_adjacency_bayesian",
            "model_based",
            "counts mobility weather",
            "connectivity driven outbreak risk",
            "transmission;forecasting",
            "10.1016/j.lansea.2023.100209",
        ),
        (
            "svd_eof",
            "spatiotemporal",
            "area by time covariate matrices",
            "coupled dominant modes",
            "transmission;transfer",
            "10.3390/insects15050366",
        ),
        (
            "maup_sensitivity",
            "multiscale",
            "multiple spatial grains",
            "scale and zoning sensitivity",
            "risk;disaggregation",
            "10.1038/s41598-024-82212-1",
        ),
        (
            "temporal_aggregation_sensitivity",
            "multiscale",
            "multiple temporal grains",
            "frequency dependent findings",
            "forecasting;transmission",
            "10.1038/s41597-024-03120-7",
        ),
        (
            "domain_similarity",
            "transfer",
            "multiple area series",
            "source target similarity",
            "transfer",
            "10.3390/insects15050366",
        ),
        (
            "population_offset_audit",
            "data_quality",
            "population denominators",
            "rate comparability",
            "risk;disaggregation",
            "10.1038/s41597-024-03120-7",
        ),
        (
            "boundary_change_audit",
            "data_quality",
            "versioned boundaries",
            "administrative split bias",
            "all",
            "10.1038/s41597-024-03120-7",
        ),
        (
            "residual_spatial_autocorrelation",
            "model_diagnostic",
            "model residuals adjacency",
            "unexplained spatial structure",
            "all",
            "10.4081/gh.2025.1379",
        ),
        (
            "rolling_origin_validation",
            "model_diagnostic",
            "forecast predictions",
            "temporal generalization",
            "forecasting",
            "10.2147/RMHP.S361106",
        ),
        (
            "spatial_block_validation",
            "model_diagnostic",
            "predictions and geography",
            "geographic generalization",
            "risk;transfer",
            "10.1038/s41598-024-82212-1",
        ),
        (
            "posterior_predictive_checks",
            "model_diagnostic",
            "Bayesian posterior draws",
            "calibration dispersion and extremes",
            "all",
            "10.4081/gh.2025.1379",
        ),
    ]
    return pd.DataFrame(
        rows,
        columns=[
            "method",
            "family",
            "required_input",
            "diagnoses",
            "downstream_uses",
            "reference_doi",
        ],
    )
